# CONFIG FOR SITE >> acmeusi.myben.site
#
[[headers]]
    for = "/*"
    [headers.values]
        #  X-Frame-Options = "SAMEORIGIN" # this prevents iframe embedding, but that is sometimes used by clients within intranet sites!
        #  Multi-value headers are expressed with multi-line strings
        cache-control = '''
            max-age=0,
            no-cache,
            must-revalidate
        '''

[[redirects]]
from = "/*"
to = "/sorry"
status = 404